language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - DB=postgresql
    - TRAVIS=true
rvm:
  - 2.1.1
before_script:
  - "bundle exec rake db:create"
notifications:
  email: true
